backend:
  name: github
  repo: weeznog/gatsby-drew-blog
  branch: master
media_folder: static/assets
# could use any type here look them up
collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true # create new files
    fields:
      - { name: title, label: Title }
      - { name: date, label: Create At, widget: date }
      - { name: body, label: Post, widget: markdown }
